@startuml
class SavWav <<static>> {
    <<const>> HEADER_SIZE : int = 44
    + {static} Save(filename:string, clip:AudioClip) : bool
    + {static} TrimSilence(clip:AudioClip, min:float) : AudioClip
    + {static} TrimSilence(samples:List<float>, min:float, channels:int, hz:int) : AudioClip
    + {static} TrimSilence(samples:List<float>, min:float, channels:int, hz:int, _3D:bool, stream:bool) : AudioClip
    {static} CreateEmpty(filepath:string) : FileStream
    {static} ConvertAndWrite(fileStream:FileStream, clip:AudioClip) : void
    {static} WriteHeader(fileStream:FileStream, clip:AudioClip) : void
}
@enduml
