@startuml
class Sequencer {
    + islooping : bool
    + OnStart(_manager:ApplicationManager) : void
    + PlayTheSequence(_sequence:NoteSequence, _source:AudioSource) : IEnumerator
}
class NoteSequence {
    + UpdateSequence() : void
    + ApplySequenceToNode(_notes:List<NoteData>) : void
    + GetData() : SequenceData
    + ApplyData(data:SequenceData) : void
}
class SequenceData {
}
class "List`1"<T> {
}
Sequencer --> "manager" ApplicationManager
NoteSequence o-> "notes<NoteData>" "List`1"
NoteSequence --> "sequenceInstrument" InstrumentType
SequenceData --> "notes<NoteData>" "List`1"
SequenceData --> "sequenceInstrument" InstrumentType
@enduml
